ex12_index:
    path: /ex12
    controller: App\Controller\Ex12Controller::index
    methods: [GET]

ex12_fill_all_tables:
    path: /ex12/fill_tables
    controller: App\Controller\Ex12Controller::fillAllTables
    methods: [POST]