ex07_index:
    path: /ex07
    controller: App\Controller\Ex07Controller::index
    methods: [GET, POST]

ex07_delete:
    path: /ex07/delete/{id}
    controller: App\Controller\Ex07Controller::delete
    methods: [POST]

ex07_update:
    path: /ex07/update/{id}
    controller: App\Controller\Ex07Controller::update
    methods: [GET, POST]
