parameters:
    person_entity_path: '%kernel.project_dir%/src/Entity/Person.php'
    marital_status_snippet_path: '%kernel.project_dir%/src/Entity/MaritalStatus.txt'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $entityFilePath: '%person_entity_path%'
            $snippetFilePath: '%marital_status_snippet_path%'
            $projectDir: '%kernel.project_dir%'

    # Injection explicite des paramètres pour TablesMigrationService
    App\Service\TablesMigrationService:
        arguments:
            $entityFilePath: '%person_entity_path%'
            $snippetFilePath: '%marital_status_snippet_path%'
            $projectDir: '%kernel.project_dir%'

    # Autres services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
