ex00_index:
    path: /ex00
    controller: App\Controller\Ex00Controller::index

ex00_create_table:
    path: /ex00/create_table
    controller: App\Controller\Ex00Controller::createTable
    methods: [POST]